CREATE SCHEMA `bank` ;

USE bank;

CREATE TABLE `bank`.`customer` (
  `C_ID` VARCHAR(10) NOT NULL,
  `CNAME` VARCHAR(20) NOT NULL,
  `MNO` INT NULL,
  `ADDRESS` VARCHAR(30) NULL,
  `CITY` VARCHAR(10) NULL,
  PRIMARY KEY (`C_ID`));
  
  
ALTER TABLE `bank`.`customer` ADD COLUMN `DOB` DATE NULL AFTER `CITY`;

ALTER TABLE `bank`.`customer` CHANGE COLUMN `ADDRESS` `ADDRESS` VARCHAR(20);